apiVersion: apps/v1
kind: ReplicaSet
# ReplicaSetのmetadata
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    # podのlabelと合わせる
    matchLabels:
      app: nginx
  template:
    # Podのmetadata
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
