apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: YWRtaW4= # admin
  password: cGFzcw== # pass

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["env"]
      envFrom:
        - secretRef:
            name: mysecret
  restartPolicy: Never
