name: pre-commit
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fastapi-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
